In [3]:
import pandas as pd
import numpy as np

In [45]:
# Importing data

immi = pd.read_csv("./immigrants-by-nationality.csv")
immi = immi[["Dist", "Nbh", "Nationality", "Number"]]
immi_original = immi.copy() 

mort = pd.read_excel("./mortality_rate.xlsx")
mort_original = mort.copy() 

rent = pd.read_excel("./rental_price.xlsx")
rent_original = rent.copy()

crime = pd.read_excel("./crime.xlsx")
crime_original = crime.copy()

#no
bars = pd.read_csv("../datasets/Data_filtered/bars.csv", index_col=0)
bars_original = bars.copy()

#no
children_places = pd.read_csv("../datasets/Data_filtered/Children_places.csv", index_col=0)
children_places_original = children_places.copy()

#tot 1s
cinema = pd.read_csv("../datasets/Data_filtered/cinema.csv", index_col=0)
cinema_original = cinema.copy()

#no
education = pd.read_csv("../datasets/Data_filtered/education.csv", index_col=0)
education_original = education.copy()

#no
education_kids = pd.read_csv("../datasets/Data_filtered/educationkids.csv", index_col=0)
education_kids = education_kids.copy()

#no
hospital = pd.read_csv("../datasets/Data_filtered/hospital.csv", index_col=0)
hospital = hospital.copy()

#no
library = pd.read_csv("../datasets/Data_filtered/library.csv", index_col=0)
library = library.copy()

#no
park = pd.read_csv("../datasets/Data_filtered/park.csv", index_col=0)
park = park.copy()

population = pd.read_csv("../datasets/Data_filtered/population.csv", index_col=0)
population = population.copy()

rental = pd.read_csv("../datasets/Data_filtered/rental.csv", index_col=0)
rental = rental.copy()

#no
sport = pd.read_csv("../datasets/Data_filtered/sport.csv", index_col=0)
sport = sport.copy() 

tenants = pd.read_csv("../datasets/Data_filtered/tenants.csv", index_col=0)
tenants = tenants.copy()

In [49]:
# Grouping immigrants by Nbh, independent of country of origin

immi_dist = immi.groupby(["Nbh","Dist"]).Number.sum().reset_index()
immi_dist

                              Nbh                 Dist  Number
0                   Baró de Viver          Sant Andreu      92
1                        Can Baró       Horta-Guinardó     473
2                     Can Peguera           Nou Barris      57
3                       Canyelles           Nou Barris     140
4                Ciutat Meridiana           Nou Barris     838
..                            ...                  ...     ...
69  la Vila Olímpica del Poblenou           Sant Martí     410
70              la Vila de Gràcia               Gràcia    3587
71                      les Corts            Les Corts    2276
72                   les Roquetes           Nou Barris     920
73                les Tres Torres  Sarrià-Sant Gervasi     702

[74 rows x 3 columns]

In [72]:
# Naming Nbh and Dist all the same

rental.columns = ['Nbh', 'rent_price']
tenants.columns = ['Nbh', 'avg_occupation']