## Immigrants, Nationalities, Districts and Neighbours
- What is the percentage of immigrants living in certain neighbourhoods? And percentage by nationality?
- Is there a link between the country of origin of immigrants and the Barcelona’s neighbourhood chosen to live?

In [1]:
import pandas as pd
import numpy as np

In [20]:
df = pd.read_csv("../datasets/Data_filtered/complete_dataset.csv", index_col=0)
df_original = df.copy()

immi = pd.read_csv("../datasets/Data_filtered/immi.csv", index_col=0)
immi.columns = ['dist', 'nbh', 'nationality', 'num_immi']
immi_original = immi.copy()

immi_nbh = pd.read_csv("../datasets/Data_filtered/immi_nbh.csv", index_col=0)
immi_nbh.columns = ['nbh', 'dist', 'num_immi']
immi_nbh_original = immi_nbh.copy()

immi_foreign = pd.read_csv("../datasets/Data_filtered/immi_foreign.csv", index_col=0)
immi_foreign.columns = ['dist', 'nbh', 'nationality', 'num_immi']
immi_foreign_original = immi_foreign.copy()

immi_foreign_nbh = pd.read_csv("../datasets/Data_filtered/immi_foreign_nbh.csv", index_col=0)
immi_foreign_nbh.columns = ['nbh', 'dist', 'num_immi']
immi_foreign_nbh_original = immi_foreign_nbh.copy()

df = pd.read_csv("../datasets/Data_filtered/complete_dataset.csv")
df["perc_immi"]=df["num_immi"]/df["population"]*100
df_original = df.copy()

## Including Spain

### Basic analysis Immi dataset
(afegir-ho despres, ocupa molt)

In [19]:
# immi.head()

In [4]:
# immi.info()

In [5]:
# immi.describe()

In [6]:
# list of nbh, ordered by highest % of immigrants
df.groupby("nbh").aggregate({"num_immi":"sum",
                             "population":"sum",
                            "perc_immi":"mean"}).sort_values("perc_immi", ascending=False)

                                       num_immi  population  perc_immi
nbh
el Barri Gòtic                           2687.0     16062.0  16.728925
Sant Pere, Santa Caterina i la Ribera    2765.0     22721.0  12.169359
la Barceloneta                           1759.0     14996.0  11.729795
el Raval                                 5400.0     47608.0  11.342631
el Besòs i el Maresme                    2016.0     23009.0   8.761789
...                                         ...         ...        ...
la Marina del Prat Vermell                 32.0      1149.0   2.785030
Can Peguera                                57.0      2271.0   2.509908
Canyelles                                 140.0      6856.0   2.042007
el Poble-sec                                0.0         0.0        NaN
la Dreta de Eixample                        0.0         0.0        NaN

[75 rows x 3 columns]

In [7]:
# list of dist, ordered by highest % of immigrants
df.groupby("dist").aggregate({"num_immi":"sum",
                             "population":"sum",
                            "perc_immi":"mean"}).sort_values("perc_immi", ascending=False)

                     num_immi  population  perc_immi
dist
Ciutat Vella          12611.0    101387.0  12.992678
Eixample              19047.0    266416.0   7.148931
Sants-Montjuïc        11683.0    181910.0   5.876830
Les Corts              4375.0     82033.0   5.616012
Gràcia                 7254.0    121347.0   5.553372
Sant Martí            12720.0    235513.0   5.417583
Nou Barris             8274.0    166579.0   4.754810
Horta-Guinardó         7799.0    168751.0   4.700067
Sarrià-Sant Gervasi    7227.0    149279.0   4.645224
Sant Andreu            6335.0    147594.0   4.636017

__*Droping rows where num_immi = 0*__

In [8]:
immi = immi[immi["num_immi"]!=0]
immi.head()

           dist                                    nbh nationality  num_immi
0  Ciutat Vella                               el Raval       Spain      1109
1  Ciutat Vella                         el Barri Gòtic       Spain       482
2  Ciutat Vella                         la Barceloneta       Spain       414
3  Ciutat Vella  Sant Pere, Santa Caterina i la Ribera       Spain       537
4      Eixample                          el Fort Pienc       Spain       663

In [9]:
# immi.info

In [10]:
# immi.describe()

__*Merging immi with immi_per*__

In [11]:
perc_immi = df[["dist", "nbh", "num_immi", "population", "perc_immi"]]
perc_immi

,dist,nbh,num_immi,population,perc_immi
0,Horta-Guinardó,Horta,1127.0,26715.0,4.218604
1,Sant Andreu,Navas,988.0,22129.0,4.464730
2,Les Corts,Pedralbes,764.0,12076.0,6.326598
3,Sant Andreu,Sant Andreu,1965.0,57183.0,3.436336
4,Eixample,Sant Antoni,2490.0,38345.0,6.493676
...,...,...,...,...,...
70,Nou Barris,les Roquetes,920.0,15590.0,5.901219
71,Sarrià-Sant Gervasi,les Tres Torres,702.0,16667.0,4.211916
72,Horta-Guinardó,la Clota,39.0,610.0,6.393443
73,Eixample,la Dreta de l'Eixample,3200.0,44052.0,7.264142
74,Sants-Montjuïc,el Poble Sec,3087.0,40228.0,7.673760

__Analyzing nbh by nationality of immigrants__

## Exluding Spain

In [39]:
# Nbh by % of foreigners vs spanish immigrants

df_foreign = pd.merge(df, immi_foreign_nbh, how="left", on=["nbh", "dist"])

df_foreign.columns = ['Unnamed: 0', 'nbh', 'bars', 'children_places', 'cinemas_theatres',
       'schools', 'pre-schools', 'hospitals', 'libraries_theatres',
       'park_gardens', 'sport_centers', 'population', 'net_density(hab/ha)',
       'avg_occupation', 'dist', 'num_immi_total', 'mort_rate', 'rent_price',
       'num_crimes', 'children_places_pop', 'cinemas_theatres_pop',
       'schools_pop', 'pre-schools_pop', 'hospitals_pop',
       'libraries_theatres_pop', 'park_gardens_pop', 'sport_centers_pop',
       'facilities_pop', 'perc_immi', 'num_immi_foreign']

df_foreign["immi_diff"]=df_foreign["num_immi_foreign"]/df_foreign["num_immi_total"]*100

df_foreign["perc_immi_foreign"]=df_foreign["num_immi_foreign"]/df_foreign["population"]*100

df_foreign[["dist", "nbh", "num_immi_total", "num_immi_foreign", "immi_diff"]].sort_values("immi_diff", ascending=False)

,dist,nbh,num_immi_total,num_immi_foreign,immi_diff
10,Ciutat Vella,el Barri Gòtic,2687.0,2205.0,82.061779
7,Ciutat Vella,"Sant Pere, Santa Caterina i la Ribera",2765.0,2228.0,80.578662
19,Ciutat Vella,el Raval,5400.0,4291.0,79.462963
21,Ciutat Vella,la Barceloneta,1759.0,1345.0,76.463900
67,Sant Andreu,la Trinitat Vella,675.0,501.0,74.222222
...,...,...,...,...,...
32,Nou Barris,Can Peguera,57.0,24.0,42.105263
33,Nou Barris,Canyelles,140.0,40.0,28.571429
62,Sants-Montjuïc,la Marina del Prat Vermell,32.0,9.0,28.125000
16,NaN,el Poble-sec,NaN,NaN,NaN
22,NaN,la Dreta de Eixample,NaN,NaN,NaN

In [41]:
# list of nbh, ordered by highest % of foreign immigrants
df_foreign.groupby("nbh").aggregate({"num_immi_foreign":"sum",
                             "population":"sum",
                            "perc_immi_foreign":"mean"}).sort_values("perc_immi_foreign", ascending=False)

,num_immi_foreign,population,perc_immi_foreign
nbh,,,
el Barri Gòtic,2205.0,16062.0,13.728054
"Sant Pere, Santa Caterina i la Ribera",2228.0,22721.0,9.805906
el Raval,4291.0,47608.0,9.013191
la Barceloneta,1345.0,14996.0,8.969058
el Besòs i el Maresme,1478.0,23009.0,6.423573
...,...,...,...
Can Peguera,24.0,2271.0,1.056803
la Marina del Prat Vermell,9.0,1149.0,0.783290
Canyelles,40.0,6856.0,0.583431
el Poble-sec,0.0,0.0,NaN
la Dreta de Eixample,0.0,0.0,NaN

In [42]:
# list of dist, ordered by highest % of foreign immigrants
df_foreign.groupby("dist").aggregate({"num_immi_foreign":"sum",
                             "population":"sum",
                            "perc_immi_foreign":"mean"}).sort_values("perc_immi_foreign", ascending=False)

                     num_immi_foreign  population  perc_immi_foreign
dist
Ciutat Vella                  10069.0    101387.0          10.379052
Eixample                      12487.0    266416.0           4.715639
Sants-Montjuïc                 7464.0    181910.0           3.558621
Sant Martí                     7994.0    235513.0           3.424302
Gràcia                         4310.0    121347.0           3.239564
Les Corts                      2420.0     82033.0           3.172486
Nou Barris                     5261.0    166579.0           2.946460
Sant Andreu                    3622.0    147594.0           2.802886
Horta-Guinardó                 4544.0    168751.0           2.683435
Sarrià-Sant Gervasi            3802.0    149279.0           2.422785

__Analyzing nbh by nationality of foreign immigrants__

In [48]:
# More frequent immigrant nationality by Neighbourhood
immi_foreign.groupby('nbh', group_keys=False).apply(lambda x: x.nlargest(3, "num_immi"))

                     dist              nbh    nationality  num_immi
649           Sant Andreu    Baró de Viver           Peru         7
279           Sant Andreu    Baró de Viver       Colombia         6
797           Sant Andreu    Baró de Viver      Argentina         6
107        Horta-Guinardó         Can Baró          Italy        27
255        Horta-Guinardó         Can Baró       Colombia        18
...                   ...              ...            ...       ...
197            Nou Barris     les Roquetes          China        37
1159           Nou Barris     les Roquetes        Ecuador        33
911   Sarrià-Sant Gervasi  les Tres Torres  United States        59
2613  Sarrià-Sant Gervasi  les Tres Torres          Japan        34
97    Sarrià-Sant Gervasi  les Tres Torres          Italy        26

[222 rows x 4 columns]

In [50]:
# 3 more frequent Dist for each country of origin
immi_dist2 = immi_dist.groupby('nationality', group_keys=False).apply(lambda x: x.nlargest(3, "num_immi"))
immi_dist2

NameError: name 'immi_dist' is not defined

In [51]:
immi_dist

NameError: name 'immi_dist' is not defined