## Importing base salary pero ho faig aqui per si de cas

In [1]:
import pandas as pd
import numpy as np
from functools import reduce

In [2]:
salary = pd.read_csv("../datasets/Data_filtered/average_wages_world.csv")

In [6]:
salary.loc[salary["TIME"]==2018]

,LOCATION,INDICATOR,SUBJECT,MEASURE,FREQUENCY,TIME,Value,Flag Codes
28,AUS,AVWAGE,TOT,USD,A,2018,53349.413615,NaN
57,AUT,AVWAGE,TOT,USD,A,2018,50868.246007,NaN
86,BEL,AVWAGE,TOT,USD,A,2018,52079.615311,NaN
115,CAN,AVWAGE,TOT,USD,A,2018,48848.522502,NaN
139,CZE,AVWAGE,TOT,USD,A,2018,26961.575591,NaN
168,DNK,AVWAGE,TOT,USD,A,2018,55253.342027,NaN
197,FIN,AVWAGE,TOT,USD,A,2018,44111.400030,NaN
226,FRA,AVWAGE,TOT,USD,A,2018,44510.133176,NaN
254,DEU,AVWAGE,TOT,USD,A,2018,49813.200120,NaN
278,GRC,AVWAGE,TOT,USD,A,2018,26670.954267,NaN
302,HUN,AVWAGE,TOT,USD,A,2018,24454.710794,NaN
331,IRL,AVWAGE,TOT,USD,A,2018,47951.852433,NaN
360,ITA,AVWAGE,TOT,USD,A,2018,37751.934636,NaN
389,JPN,AVWAGE,TOT,USD,A,2018,40573.377648,NaN
418,KOR,AVWAGE,TOT,USD,A,2018,39471.711918,NaN
447,LUX,AVWAGE,TOT,USD,A,2018,65448.611952,NaN
476,MEX,AVWAGE,TOT,USD,A,2018,16297.708306,NaN
505,NLD,AVWAGE,TOT,USD,A,2018,54261.682445,NaN
534,NOR,AVWAGE,TOT,USD,A,2018,50955.829840,NaN
558,POL,AVWAGE,TOT,USD,A,2018,29109.043759,NaN
582,PRT,AVWAGE,TOT,USD,A,2018,25487.063696,NaN
607,SVK,AVWAGE,TOT,USD,A,2018,25356.682293,NaN
636,ESP,AVWAGE,TOT,USD,A,2018,38761.184570,NaN
665,SWE,AVWAGE,TOT,USD,A,2018,44196.239452,NaN
694,CHE,AVWAGE,TOT,USD,A,2018,64108.550761,NaN
723,GBR,AVWAGE,TOT,USD,A,2018,44770.049741,NaN
752,USA,AVWAGE,TOT,USD,A,2018,63093.014643,NaN
776,EST,AVWAGE,TOT,USD,A,2018,26898.103459,NaN
800,ISR,AVWAGE,TOT,USD,A,2018,37655.301110,NaN
824,SVN,AVWAGE,TOT,USD,A,2018,37321.908671,NaN
853,OECD,AVWAGE,TOT,USD,A,2018,46686.337814,NaN
882,ISL,AVWAGE,TOT,USD,A,2018,66504.281168,NaN
911,NZL,AVWAGE,TOT,USD,A,2018,42324.874204,NaN
934,CHL,AVWAGE,TOT,USD,A,2018,27124.711146,NaN
957,LVA,AVWAGE,TOT,USD,A,2018,25586.197966,NaN
981,LTU,AVWAGE,TOT,USD,A,2018,26429.228188,NaN